#=======================================服务器端口配置=======================================
server:
  port: 8081

#=======================================spring配置=======================================
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bbtv?haracterEncoding=utf8&useSSL=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    druid:
#      url: jdbc:mysql://localhost:3306/bbtv?useUnicode=true&useSSL=true&autoReconnect=true
#      username: root
#      password: admin
#      driverClassName: com.mysql.jdbc.Driver
      #最大活跃数
      max-active: 20
      #初始化数量
      initial-size: 1
      #最大连接等待超时时间
      max-wait: 60000
      #打开PSCache 并且指定每个连接的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #通过connectionProperties属性来打开mergeSql功能  慢sql记录
      #connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, log4j
      time-between-connect-error-millis: 10000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
#  mvc:
#    view:
#      prefix: WEB-INF/jsp
#      suffix: .jsp
#=======================================Thymeleaf配置=======================================
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    #开发时关闭缓存,不然没办法看见实时页面
    cache: false
    prefix: classpath:/templates
    servlet:
      content-type: text/html

#=======================================redis配置=======================================
#  redis:
#    host: localhost
#    port: 6379
#    database: 1
#    timeout: 5000
#    pool:
#      max-active: 8
#      max-idle: 500
#      min-idle: 0
#      max-wait: -1

#=======================================mybatis配置=======================================
mybatis:
  mapper-locations: classpath*:com.xuwenxing.bbtv.dao/*Mapper*.xml
  type-aliases-package:  com.xuwenxing.bbtv.dao
